"""add rejection reason to posts

Revision ID: 557a0e33b12c
Revises: 80b3a9e0b9cf
Create Date: 2026-08-17 23:09:44.350157

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '557a0e33b12c'
down_revision: Union[str, Sequence[str], None] = '80b3a9e0b9cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('rejection_reason', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'rejection_reason')
    # ### end Alembic commands ###
