"""create content tables

Revision ID: 80b3a9e0b9cf
Revises: 614ce5cf15d3
Create Date: 2026-08-17 01:52:50.478835

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '80b3a9e0b9cf'
down_revision: Union[str, Sequence[str], None] = '614ce5cf15d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    op.create_table('categories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('order_index', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon_url', sa.Text(), nullable=True),
    sa.Column('color_hex', sa.String(length=7), nullable=True),
    sa.Column('is_featured', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('seo_title', sa.String(length=255), nullable=True),
    sa.Column('seo_description', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['categories.id'], name=op.f('fk_categories_parent_id_categories')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_categories')),
    sa.UniqueConstraint('slug', name=op.f('uq_categories_slug'))
    )
    op.create_index('ix_categories_parent_id', 'categories', ['parent_id'], unique=False)
    op.create_table('newsletter_subscribers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('subscribed', 'unsubscribed', 'bounced', name='newsletter_status'), server_default=sa.text("'subscribed'"), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('subscribed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_newsletter_subscribers')),
    sa.UniqueConstraint('email', name=op.f('uq_newsletter_subscribers_email'))
    )
    op.create_table('redirects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('old_path', sa.String(length=500), nullable=False),
    sa.Column('new_path', sa.String(length=500), nullable=False),
    sa.Column('redirect_type', sa.SmallInteger(), server_default=sa.text('301'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_redirects')),
    sa.UniqueConstraint('old_path', name=op.f('uq_redirects_old_path'))
    )
    op.create_table('tags',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tags')),
    sa.UniqueConstraint('slug', name=op.f('uq_tags_slug'))
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_audit_logs_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_index('ix_audit_logs_entity', 'audit_logs', ['entity_type', 'entity_id'], unique=False)
    op.create_index('ix_audit_logs_user_id', 'audit_logs', ['user_id'], unique=False)
    op.create_table('media',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('uploader_id', sa.UUID(), nullable=False),
    sa.Column('file_url', sa.Text(), nullable=False),
    sa.Column('file_type', sa.String(length=20), nullable=False),
    sa.Column('alt_text', sa.String(length=255), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('size_kb', sa.Integer(), nullable=True),
    sa.Column('folder', sa.String(length=100), server_default=sa.text("'uncategorized'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['uploader_id'], ['users.id'], name=op.f('fk_media_uploader_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_media'))
    )
    op.create_table('posts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('excerpt', sa.String(length=500), nullable=True),
    sa.Column('content_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('content_html', sa.Text(), nullable=True),
    sa.Column('content_tsv', postgresql.TSVECTOR(), sa.Computed("setweight(to_tsvector('english', coalesce(title, '')), 'A') || setweight(to_tsvector('english', coalesce(excerpt, '')), 'B') || setweight(to_tsvector('english', coalesce(content_html, '')), 'C')", persisted=True), nullable=False),
    sa.Column('featured_image_url', sa.Text(), nullable=True),
    sa.Column('author_id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'pending_review', 'published', 'rejected', 'scheduled', name='post_status'), nullable=False),
    sa.Column('view_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('is_trending', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('reading_time_minutes', sa.SmallInteger(), nullable=True),
    sa.Column('meta_title', sa.String(length=255), nullable=True),
    sa.Column('meta_description', sa.String(length=500), nullable=True),
    sa.Column('canonical_url', sa.Text(), nullable=True),
    sa.Column('og_image_url', sa.Text(), nullable=True),
    sa.Column('schema_type', sa.String(length=50), server_default=sa.text("'TechArticle'"), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name=op.f('fk_posts_author_id_users')),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('fk_posts_category_id_categories')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_posts')),
    sa.UniqueConstraint('slug', name=op.f('uq_posts_slug'))
    )
    op.create_index('idx_posts_content_tsv', 'posts', ['content_tsv'], unique=False, postgresql_using='gin')
    op.create_index('idx_posts_title_trgm', 'posts', ['title'], unique=False, postgresql_using='gin', postgresql_ops={'title': 'gin_trgm_ops'})
    op.create_index('ix_posts_author_id', 'posts', ['author_id'], unique=False)
    op.create_index('ix_posts_category_id', 'posts', ['category_id'], unique=False)
    op.create_index('ix_posts_is_trending', 'posts', ['is_trending'], unique=False)
    op.create_index('ix_posts_published_at', 'posts', ['published_at'], unique=False)
    op.create_index('ix_posts_status', 'posts', ['status'], unique=False)
    op.create_table('comments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('post_id', sa.UUID(), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('user_name', sa.String(length=100), nullable=False),
    sa.Column('user_email', sa.String(length=255), nullable=False),
    sa.Column('comment_text', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'spam', 'rejected', name='comment_status'), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['comments.id'], name=op.f('fk_comments_parent_id_comments')),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], name=op.f('fk_comments_post_id_posts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_comments'))
    )
    op.create_index('ix_comments_post_id', 'comments', ['post_id'], unique=False)
    op.create_index('ix_comments_status', 'comments', ['status'], unique=False)
    op.create_table('downloadable_assets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('post_id', sa.UUID(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_url', sa.Text(), nullable=False),
    sa.Column('file_type', sa.String(length=20), nullable=False),
    sa.Column('file_size_kb', sa.Integer(), nullable=True),
    sa.Column('download_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], name=op.f('fk_downloadable_assets_post_id_posts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_downloadable_assets'))
    )
    op.create_table('post_tags',
    sa.Column('post_id', sa.UUID(), nullable=False),
    sa.Column('tag_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], name=op.f('fk_post_tags_post_id_posts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], name=op.f('fk_post_tags_tag_id_tags'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('post_id', 'tag_id', name=op.f('pk_post_tags'))
    )
    op.create_table('post_views',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('post_id', sa.UUID(), nullable=False),
    sa.Column('viewed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ip_hash', sa.String(length=64), nullable=True),
    sa.Column('referrer', sa.Text(), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], name=op.f('fk_post_views_post_id_posts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_post_views'))
    )
    op.create_index('ix_post_views_post_id_viewed_at', 'post_views', ['post_id', 'viewed_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_post_views_post_id_viewed_at', table_name='post_views')
    op.drop_table('post_views')
    op.drop_table('post_tags')
    op.drop_table('downloadable_assets')
    op.drop_index('ix_comments_status', table_name='comments')
    op.drop_index('ix_comments_post_id', table_name='comments')
    op.drop_table('comments')
    op.drop_index('ix_posts_status', table_name='posts')
    op.drop_index('ix_posts_published_at', table_name='posts')
    op.drop_index('ix_posts_is_trending', table_name='posts')
    op.drop_index('ix_posts_category_id', table_name='posts')
    op.drop_index('ix_posts_author_id', table_name='posts')
    op.drop_index('idx_posts_title_trgm', table_name='posts', postgresql_using='gin', postgresql_ops={'title': 'gin_trgm_ops'})
    op.drop_index('idx_posts_content_tsv', table_name='posts', postgresql_using='gin')
    op.drop_table('posts')
    op.drop_table('media')
    op.drop_index('ix_audit_logs_user_id', table_name='audit_logs')
    op.drop_index('ix_audit_logs_entity', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_table('tags')
    op.drop_table('redirects')
    op.drop_table('newsletter_subscribers')
    op.drop_index('ix_categories_parent_id', table_name='categories')
    op.drop_table('categories')
    sa.Enum(name='post_status').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='comment_status').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='newsletter_status').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
