"""add sync columns to newsletter subscribers

Revision ID: a3f8c2d91b47
Revises: 557a0e33b12c
Create Date: 2026-08-18 11:12:03.210485

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3f8c2d91b47'
down_revision: Union[str, Sequence[str], None] = '557a0e33b12c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('newsletter_subscribers', sa.Column('unsubscribed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('newsletter_subscribers', sa.Column('synced_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('newsletter_subscribers', 'synced_at')
    op.drop_column('newsletter_subscribers', 'unsubscribed_at')
    # ### end Alembic commands ###
